// <auto-generated />
namespace AT_T_31_10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WrongProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WrongProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221822298_WrongProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
