// <auto-generated />
namespace AT_T_31_10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JOBRECRUITER2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JOBRECRUITER2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711020820114_JOBRECRUITER2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
