// <auto-generated />
namespace AT_T_31_10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JOBRECRUITER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JOBRECRUITER));
        
        string IMigrationMetadata.Id
        {
            get { return "201711020818162_JOBRECRUITER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
