// <auto-generated />
namespace AT_T_31_10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UnRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201711081602019_UnRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
